package id.alfadigital.unittest.db.postgresql.model;

public class TbTransactionPromo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tb_transaction_promo.tbto_id
     *
     * @mbg.generated
     */
    private Long tbtoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tb_transaction_promo.tbto_no
     *
     * @mbg.generated
     */
    private String tbtoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tb_transaction_promo.tbto_amount
     *
     * @mbg.generated
     */
    private Integer tbtoAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tb_transaction_promo.tbto_discount
     *
     * @mbg.generated
     */
    private Integer tbtoDiscount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tb_transaction_promo.tbto_id
     *
     * @return the value of public.tb_transaction_promo.tbto_id
     * @mbg.generated
     */
    public Long getTbtoId() {
        return tbtoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tb_transaction_promo.tbto_id
     *
     * @param tbtoId the value for public.tb_transaction_promo.tbto_id
     * @mbg.generated
     */
    public void setTbtoId(Long tbtoId) {
        this.tbtoId = tbtoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tb_transaction_promo.tbto_no
     *
     * @return the value of public.tb_transaction_promo.tbto_no
     * @mbg.generated
     */
    public String getTbtoNo() {
        return tbtoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tb_transaction_promo.tbto_no
     *
     * @param tbtoNo the value for public.tb_transaction_promo.tbto_no
     * @mbg.generated
     */
    public void setTbtoNo(String tbtoNo) {
        this.tbtoNo = tbtoNo == null ? null : tbtoNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tb_transaction_promo.tbto_amount
     *
     * @return the value of public.tb_transaction_promo.tbto_amount
     * @mbg.generated
     */
    public Integer getTbtoAmount() {
        return tbtoAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tb_transaction_promo.tbto_amount
     *
     * @param tbtoAmount the value for public.tb_transaction_promo.tbto_amount
     * @mbg.generated
     */
    public void setTbtoAmount(Integer tbtoAmount) {
        this.tbtoAmount = tbtoAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tb_transaction_promo.tbto_discount
     *
     * @return the value of public.tb_transaction_promo.tbto_discount
     * @mbg.generated
     */
    public Integer getTbtoDiscount() {
        return tbtoDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tb_transaction_promo.tbto_discount
     *
     * @param tbtoDiscount the value for public.tb_transaction_promo.tbto_discount
     * @mbg.generated
     */
    public void setTbtoDiscount(Integer tbtoDiscount) {
        this.tbtoDiscount = tbtoDiscount;
    }
}