package id.alfadigital.unittest.db.postgresql.mapper;

import id.alfadigital.unittest.db.postgresql.model.TbMasterPromo;
import id.alfadigital.unittest.db.postgresql.model.TbMasterPromoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TbMasterPromoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_master_promo
     *
     * @mbg.generated
     */
    long countByExample(TbMasterPromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_master_promo
     *
     * @mbg.generated
     */
    int deleteByExample(TbMasterPromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_master_promo
     *
     * @mbg.generated
     */
    int insert(TbMasterPromo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_master_promo
     *
     * @mbg.generated
     */
    int insertSelective(TbMasterPromo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_master_promo
     *
     * @mbg.generated
     */
    List<TbMasterPromo> selectByExample(TbMasterPromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_master_promo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbMasterPromo record, @Param("example") TbMasterPromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tb_master_promo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbMasterPromo record, @Param("example") TbMasterPromoExample example);
}